image: docker:latest

services:
  - docker:dind

stages:
  - build
  - publish

variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $DOCKERHUB_USERNAME/lab:latest

before_script:
  - chmod +x mvnw
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

build:
  stage: build
  script:
    - echo "In build phase"
    - export JAVA_HOME=$(dirname $(dirname $(readlink $(which javac))))
    - ./mvnw package -Pprod verify jib:dockerBuild -DskipTests --image=$CONTAINER_TEST_IMAGE
    - docker push $CONTAINER_TEST_IMAGE

publish-image:
  stage: publish
  script:
    - echo "In publish phase"
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
