image: maven:3.8.4-openjdk-11

services:
  - docker:dind

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .maven/

stages:
  - check
  - build
  - package
  - release

before_script:
  - export NG_CLI_ANALYTICS="false"
  - export MAVEN_USER_HOME=`pwd`/.maven
  - echo "Docker Version:"
  - docker version
  - echo "Environment Variables:"
  - printenv
  - echo "Your Other Commands..."

docker-push:
  stage: release
  variables:
    REGISTRY_URL: registry.gitlab.com
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA
  script:
    - bash mvnw -ntp package -Pprod verify jib:dockerBuild -DskipTests -Djib.to.image=$IMAGE_TAG -Djib.to.auth.username=$DOCKERHUB_USERNAME -Djib.to.auth.password=$DOCKERHUB_PASSWORD -Dmaven.repo.local=$MAVEN_USER_HOME -Dmaven.compiler.release=11
