---
- name: Deploy Application to Minikube
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig: "/cygdrive/c/Users/HP/.kube/config"

  tasks:
    - name: Debug Python Path
      debug:
        var: ansible_python | default('Python not found')

    - name: Apply Deployment and Service
      k8s:
        definition: "{{ lookup('file', 'deployment.yml') | from_yaml }}"
        state: present
        kubeconfig: "{{ kubeconfig }}"
        validate: false  # Disable validation temporarily
      environment:
        ANSIBLE_REMOTE_TEMP: "{{ remote_tmp }}"  # Set the remote_tmp for the k8s module

    - name: Apply Service
      k8s:
        definition: "{{ lookup('file', 'service.yml') | from_yaml }}"
        state: present
        kubeconfig: "{{ kubeconfig }}"
        validate: false  # Disable validation temporarily
      environment:
        ANSIBLE_REMOTE_TEMP: "{{ remote_tmp }}"  # Set the remote_tmp for the k8s module
