---
- name: Deploy Application to Kubernetes
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    remote_tmp: "/tmp/ansible-{{ ansible_user }}"
    kubeconfig: "{{ kubeconfig }}"  # Update this with the correct path

  tasks:
    - name: Set remote_tmp
      set_fact:
        remote_tmp: "{{ remote_tmp }}"

    - name: Debug ansible_user
      debug:
        var: ansible_user

    - name: Debug Python Path
      debug:
        var: ansible_python | default('Python not found')

    - name: Apply Deployment
      k8s:
        definition: "{{ lookup('file', 'deployment.yml') | from_yaml }}"
        state: present
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
        ANSIBLE_REMOTE_TEMP: "{{ remote_tmp }}"  # Set the remote_tmp for the k8s module

    - name: Apply Service
      k8s:
        definition: "{{ lookup('file', 'service.yml') | from_yaml }}"
        state: present
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
        ANSIBLE_REMOTE_TEMP: "{{ remote_tmp }}"  # Set the remote_tmp for the k8s module
