- name: Deploy Application to Minikube
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    kubeconfig: "/cygdrive/c/Users/HP/.kube/config" # Update this with the correct path
    minikube_ip: "127.0.0.1"

  tasks:
    - name: Apply Deployment and Service
      command: kubectl apply -f "{{ item }}"
      loop:
        - deployment.yml
        - service.yml
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
        K8S_API_SERVER: "https://{{ minikube_ip }}:55305"
