- name: Deploy Application to Minikube
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Deployment
      command: kubectl apply -f /path/to/deployment.yml
      environment:
        KUBECONFIG: /cygdrive/c/Users/HP/.kube/config
        K8S_API_SERVER: https://192.168.49.2:8443  # Use your Minikube IP
      ignore_errors: yes

    - name: Apply Service
      command: kubectl apply -f /path/to/service.yml
      environment:
        KUBECONFIG: /cygdrive/c/Users/HP/.kube/config
        K8S_API_SERVER: https://192.168.49.2:8443  # Use your Minikube IP
      ignore_errors: yes
