---
- name: Deploy Application to Kubernetes
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    ansible_user: "DESKTOP-7JBHK4H"

  tasks:
    - name: Set remote_tmp
      set_fact:
        remote_tmp: "/tmp/ansible-{{ ansible_user }}"

    - name: Apply Deployment
      k8s:
        definition: "{{ lookup('file', 'deployment.yml') | from_yaml }}"
        state: present
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
        remote_tmp: "{{ remote_tmp }}"

    - name: Apply Service
      k8s:
        definition: "{{ lookup('file', 'service.yml') | from_yaml }}"
        state: present
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
        remote_tmp: "{{ remote_tmp }}"
