---
- name: Deploy Application to Kubernetes
  hosts: localhost
  gather_facts: false
  connection: local  # Set the connection type to local
  tasks:
    - name: Load Kubernetes Configuration
      command: kubectl config view --minify --flatten
      register: kubeconfig_output

    - name: Set Kubernetes Configuration
      set_fact:
        kubeconfig_content: "{{ kubeconfig_output.stdout }}"
      when: kubeconfig_output.rc == 0

    - name: Debug Kubernetes Configuration
      debug:
        var: kubeconfig_content

    # Add your tasks to deploy the application using kubectl
    - name: Apply Deployment
      command: kubectl apply -f your_deployment_file.yml
      environment:
        KUBECONFIG: "{{ kubeconfig_content }}"
