---
- name: Deploy Application to Kubernetes
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Apply Deployment
      k8s:
        definition: "{{ lookup('file', 'deployment.yml') | from_yaml }}"
        state: present
      environment:
        KUBECONFIG: "{{ kubeconfig }}"

    - name: Apply Service
      k8s:
        definition: "{{ lookup('file', 'service.yml') | from_yaml }}"
        state: present
      environment:
        KUBECONFIG: "{{ kubeconfig }}"
