apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-biomedicale-nmm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-biomedicale-nmm
  template:
    metadata:
      labels:
        app: app-biomedicale-nmm
    spec:
      containers:
        - name: app-biomedicale-nmm
          image: hafidnid/app_biomedicale_deploy_finale_f3:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-biomedicale-nmm
spec:
  selector:
    app: app-biomedicale-nmm
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
